language: node_js
node_js:
- 5.2.0
before_install:
- npm install
script:
- webpack
sudo: false
before_deploy:
- npm-prepublish --verbose
deploy:
- provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  on:
    tags: true
env:
  global:
  - secure: kVL6ZuGcm8HWxzYh4FKVLpvd1DCK8giW6MmjFSglyCLO0kuDIArftXCyodzWUagjEd6BPSP4LJTeqBY8Hk0jT4sZ2c9q0EgVgS3r6o9+6saJhnbI1tAMyCn5x4AvpkAzsLGnsgxL7Gq/fjrZqrtA/oL/wPQ6HaG0TYRZNBk0rnEg0UU2wH7bRdz1gI9DnKbQVhJjAw1p5rxe2DggI8Ijt1B+LHz63kwlyvj7IEFxG7PDsbljci0qbBMft5Pkd6f3nGqHK0q0t0rt1yhARP0GQ7gwMAK6E2Y4CSEpfBHe0VtR3FIFjAk2VxmsoACS3+4u6I5jPzuFyKJ98Xi947XBxUo4l5GkPUgeZMXiEQUCiQNpnIluaZFy/Cmpxs6Na71kSRPFFNfhMN7mdFZ2vbmxejcc4Ui9nUAXiNMwqpq0iR20eVd6HVD7clGeQvT4nCTvRtWH3eDhFXjIhC6c6AvW5TRLX5EL9s1gW1hv89ZwApWnqbZ5qaR4hP2RvwBnNU8RyOUgKV4Lyl3/uLPG3AVUBKFu4Fk6+WGYmFeaBbVt8VKH+Q+Hmp9UrlodLUpJXF87mV56pfSLkFy5lzFi90Dt6qnaNUqa6O8gA/qd1mYNfnvFpXoWWTJfGsffP4GNc0YuTka0VdmtSdqus33L4wNj0ztpQuZaGGursgVItIO/7cc=
  - secure: sXEpbxoqqsoH+CfKDOUPgceMIiuArDUCRvEvLOrae+lDc565MKgHL/6c18vILm3KDLjdSSSwnrEMXQWwTS+5hQ8Grb6G8LzupxyfQEa6EiY0geGnCZDn+zL7+RNIGjXMUOTdFhV8RXdVbsONibY+pWxduVt7Go7uGmcgATLTZZmtJx+ZVSb6cjhvwo44gFkyhg9CA6MzxCJ49ZF8bKrfcx9evuiQN9Jp6AZby86KM4sZgb1tjk1wliqAjCeguFlBWC99ZKhF5sVdwHSt8FwfAzaQiggB5A6u+hNgAnoXcDg9CICcPtrLVvS5T8LNrb40eOk5RZSJ/Xf6ppNpO5G64AkU3Q0A2gUxhLNedVQmJK0LVzf0IeSwWH5JDopYlKsGohdM0lYxcNQzWMMBZTIdXYliYA3xuAZGn/Da+e91zT3xp6AyoW6CbpmJD9eh3LAq73oMBZQcigxawyRCieJ+zdstzEeuJwLou+byYE4RuKgv78iDewyPWF7a5ZTrc5b8joqpJEhBrryV2XC/20XC/ASdyC/i6UeTzndp7hsj54GGoWhbmrUw3brloSPt3MFvh8zi/JLTwAaSq4xdv9dkeLZHaz4mj4LK8yzOYqjPzyRhxXQEP2msb2IjARFvMa6GopqTZRfdzPu//d6WsLDGQ9Av7Mtm7a3VEaASAc2CO9A=
