language: node_js
node_js:
- 0.12.4
install:
- npm install -g npm
- npm install -g gulp
- npm install -g bower
- npm install
- bower install
script:
- gulp clean
- gulp preprocessors
- gulp test
- gulp useref
- gulp copy-files
- gulp remove-code
sudo: false
after_success:
- gulp coveralls